.TH RECS\-ASSERT 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-assert \- Asserts that every record in the stream must pass the given expression

.SH SYNOPSIS
.B recs assert [options] <expression> [files...]

.SH DESCRIPTION
Asserts that every record in the stream must pass the given expression. The expression is evaluated on each record with r set to the current Record object and line set to the current line number (starting at 1). If the expression does not evaluate to true, processing is immediately aborted and an error message is printed.
.PP

.SH OPTIONS
.TP
\fB--diagnostic\fR, \fB-d\fR \fI<text>\fR
Include this diagnostic string in any failed assertion errors.
.TP
\fB--verbose\fR, \fB-v\fR
Verbose output for failed assertions; dumps the current record.

.SH EXAMPLES
Require each record to have a date field
.PP
.RS 4
.nf
\fBrecs assert \'r.date\'\fR
.fi
.RE

Assert all values are positive with a diagnostic
.PP
.RS 4
.nf
\fBrecs assert -d \'values must be positive\' \'r.value > 0\'\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-grep\fR(1), \fBrecs\-xform\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

