.TH RECS\-TOCSV 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-tocsv \- Outputs records as CSV formatted lines

.SH SYNOPSIS
.B recs tocsv [options] [files...]

.SH DESCRIPTION
Outputs records as CSV formatted lines. With the \-\-delim option, it can output TSV or other line\-based formats with character\-separated fields.
.PP

.SH OPTIONS
.TP
\fB--key\fR, \fB-k\fR \fI<keyspec>\fR
Comma separated keys to output. Defaults to all fields in the first record. May be a keyspec or a keygroup.
.TP
\fB--noheader\fR, \fB--nh\fR
Do not output headers on the first line.
.TP
\fB--delim\fR, \fB-d\fR \fI<character>\fR
Field delimiter character to use when outputting lines (default \',\').

.SH EXAMPLES
Print records to csv format with headers
.PP
.RS 4
.nf
\fBrecs tocsv myrecords\fR
.fi
.RE

Only print time and a nested value of stat/avg
.PP
.RS 4
.nf
\fB... | recs tocsv --key time,stat/avg\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-fromcsv\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

