.TH RECS\-SUBSTREAM 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-substream \- Filter to a range of records delimited from when the begin snippet becomes true to when the end snippet becomes true, i

.SH SYNOPSIS
.B recs substream [options] [files...]

.SH DESCRIPTION
Filter to a range of records delimited from when the begin snippet becomes true to when the end snippet becomes true, i.e. [begin, end]. Compare to Perl\'s inclusive, bistable ".." range operator.
.PP

.SH OPTIONS
.TP
\fB--begin\fR, \fB-b\fR \fI<snippet>\fR
Begin outputting records when this snippet becomes true. If omitted, output starts from the beginning of the stream.
.TP
\fB--end\fR, \fB-e\fR \fI<snippet>\fR
Stop outputting records after this snippet becomes true. If omitted, outputs to the end of the stream.

.SH EXAMPLES
Filter to records within a specific time window
.PP
.RS 4
.nf
\fBrecs substream -b \'r.time >= "2013-11-07 22:42"\' -e \'r.time > "2013-11-07 22:43"\'\fR
.fi
.RE

Truncate past a specific date
.PP
.RS 4
.nf
\fBrecs substream -e \'r.endTime.includes("Nov 07")\'\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-grep\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

