.TH RECS\-GENERATE 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-generate \- Execute an expression for each record to generate new records

.SH SYNOPSIS
.B recs generate [options] <expression> [files...]

.SH DESCRIPTION
Execute an expression for each record to generate new records. The expression should return an array of new record objects (or a single record). Each generated record gets a chain link back to the original input record under the \'_chain\' key (configurable via \-\-keychain).
.PP

.SH OPTIONS
.TP
\fB--keychain\fR \fI<name>\fR
Key name for the chain link back to the original record. Default is \'_chain\'. May be a key spec.
.TP
\fB--passthrough\fR
Emit the input record in addition to the generated records.

.SH EXAMPLES
Generate sub\-records from a feed and chain back to the original
.PP
.RS 4
.nf
\fBrecs generate \'fetchFeed(r.url).map(item => ({ title: item.title }))\'\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-xform\fR(1), \fBrecs\-chain\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

