.TH RECS\-GREP 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-grep \- Filter records where an expression evaluates to true

.SH SYNOPSIS
.B recs grep [options] <expression> [files...]

.SH DESCRIPTION
Filter records where an expression evaluates to true. The expression is evaluated on each record with r set to the current Record object and line set to the current line number (starting at 1). Records for which the expression is truthy are passed through.
.PP

.SH OPTIONS
.TP
\fB--invert-match\fR, \fB-v\fR
Anti\-match: records NOT matching the expression will be returned.
.TP
\fB--context\fR, \fB-C\fR \fI<NUM>\fR
Provide NUM records of context around matches (equivalent to \-A NUM and \-B NUM).
.TP
\fB--after-context\fR, \fB-A\fR \fI<NUM>\fR
Print out NUM following records after a match.
.TP
\fB--before-context\fR, \fB-B\fR \fI<NUM>\fR
Print out the previous NUM records on a match.

.SH EXAMPLES
Filter to records with field \'name\' equal to \'John\'
.PP
.RS 4
.nf
\fBrecs grep \'r.name === "John"\'\fR
.fi
.RE

Find records without ppid equal to 3456
.PP
.RS 4
.nf
\fBrecs grep -v \'r.ppid === 3456\'\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-xform\fR(1), \fBrecs\-assert\fR(1), \fBrecs\-substream\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

