.TH RECS\-TOTABLE 1 "2026-02-21" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-totable \- Pretty prints a table of records to the screen

.SH SYNOPSIS
.B recs totable [options] [files...]

.SH DESCRIPTION
Pretty prints a table of records to the screen. Will read in the entire record stream to determine column size and number of columns.
.PP

.SH OPTIONS
.TP
\fB--no-header\fR, \fB-n\fR
Do not print column headers.
.TP
\fB--key\fR, \fB-k\fR, \fB--field\fR, \fB-f\fR \fI<field name>\fR
Specifies fields to put in the table. May be comma separated or specified multiple times. May be a keyspec or a keygroup.
.TP
\fB--spreadsheet\fR, \fB-s\fR
Print in spreadsheet\-compatible format. Does not print line of dashes after header. Separates by single character rather than series of spaces.
.TP
\fB--delim\fR, \fB-d\fR \fI<string>\fR
Only useful with \-\-spreadsheet. Delimit with the given string rather than the default of a tab.
.TP
\fB--clear\fR
Put blanks in cells where all of the row so far matches the row above.

.SH EXAMPLES
Display a table
.PP
.RS 4
.nf
\fBrecs totable\fR
.fi
.RE

Display only one field
.PP
.RS 4
.nf
\fBrecs totable -f foo\fR
.fi
.RE

Display two fields without a header
.PP
.RS 4
.nf
\fBrecs totable -f foo -f bar --no-header\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-toprettyprint\fR(1), \fBrecs\-tohtml\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

