=head1 NAME

recs-fromxml

=head1 recs-fromxml --help-all

 Usage: recs-fromxml <args> [<URIs>]
    Reads either from STDIN or from the specified URIs. Parses the xml documents,
    and creates records for the specified elements. If multiple element types are
    specified, will add a {'element' => element name} field to the output record.
 
    --element <elements>         May be comma separated, may be specified
                                 multiple times. Sets the elements/attributes to
                                 print records for
    --nested                     search for elements at all levels of the xml
                                 document
    --filename-key|fk <keyspec>  Add a key with the source filename (if no
                                 filename is applicable will put NONE)
 
   Help Options:
       --help  This help screen
 
 Examples:
    Create records for the bar element at the top level of myXMLDoc
       recs-fromxml --element bar file:myXMLDoc
    Create records for all foo and bar elements from the URL
       recs-fromxml --element foo,bar --nested http://google.com

=head1 SEE ALSO

=over

=item * See L<App::RecordStream> for an overview of the scripts and the system

=item * Run C<recs examples> or see L<App::RecordStream::Manual::Examples> for a set of simple recs examples

=item * Run C<recs story> or see L<App::RecordStream::Manual::Story> for a humorous introduction to RecordStream

=item * Every command has a C<--help> mode available to print out usage and
examples for the particular command, just like the output above.

=back

