=head1 NAME

recs-collate

=head1 recs-collate --help-all

 Help from: --help-aggregators:
 average, avg: averages provided field
 cb, countby: counts by unique value for a field
 concat, concatenate: concatenate values from provided field
 corr, correl, correlation: find correlation of provided fields
 count, ct: counts (non-unique) records
 cov, covar, covariance: find covariance of provided fields
 dcount, dct, distinctcount, distinctct: count unique values from provided field
 first: first value for a field
 firstrec, firstrecord: first record
 last: last value for a field
 lastrec, lastrecord: last record seen
 linearregression, linreg: perform a linear regression of provided fields, dumping various statistics
 max, maximum: maximum value for a field
 min, minimum: minimum value for a field
 mode: most common value for a field
 perc, percentile: value of pXX for field
 percentilemap, percmap: map of percentile values for field
 recformax, recformaximum, recordformax, recordformaximum: returns the record corresponding to the maximum value for a field
 recformin, recforminimum, recordformin, recordforminimum: returns the record corresponding to the minimum value for a field
 records, recs: returns an arrayref of all records
 stddev: find standard deviation of provided field
 sum: sums provided field
 uconcat, uconcatenate: concatenate unique values from provided field
 valuestokeys, vk: use one key-value as a key for a different value in the record
 var, variance: find variance of provided field
 
 Help from: --help-basic:
 Usage: recs-collate <args> [<files>]
    Take records, grouped togther by --keys, and compute statistics (like
    average, count, sum, concat, etc) within those groups.
 
    For starting with collate, try doing single --key collates with some number
    of aggregators (list available in --list-agrregators)
 
 Arguments:
    --dlaggregator|-A ...                         Specify a domain language
                                                  aggregate. See "Domain Language
                                                  Integration" below.
    --aggregator|-a <aggregators>                 Colon separated list of
                                                  aggregate field specifiers. See
                                                  "Aggregates" section below.
    --mr-agg <name> <map> <reduce> <squish>       Specify a map reduce
                                                  aggregator via 3 snippets,
                                                  similar to mr_agg() from the
                                                  domain language.
    --ii-agg <name> <initial> <combine> <squish>  Specify an inject into
                                                  aggregator via 3 snippets,
                                                  similar to ii_agg() from the
                                                  domain language.
    --incremental                                 Output a record every time an
                                                  input record is added to a
                                                  clump (instead of everytime a
                                                  clump is flushed).
    --key|-k <keys>                               Comma separated list of key
                                                  fields. May be a key spec or
                                                  key group
    --dlkey|-K ...                                Specify a domain language key.
                                                  See "Domain Language
                                                  Integration" section in --help-
                                                  more.
    --size|--sz|-n <number>                       Number of running clumps to
                                                  keep.
    --adjacent|-1                                 Only group together adjacent
                                                  records. Avoids spooling
                                                  records into memeory
    --cube                                        See "Cubing" section in --help-
                                                  more.
    --clumper ...                                 Use this clumper to group
                                                  records. May be specified
                                                  multiple times. See --help-
                                                  clumping.
    --dlclumper ...                               Use this domain language
                                                  clumper to group records. May
                                                  be specified multiple times.
                                                  See --help-clumping.
    --list-aggregators|--list                     Bail and output a list of
                                                  aggregators
    --show-aggregator <aggregator>                Bail and output this
                                                  aggregator's detailed usage.
    --list-clumpers                               Bail and output a list of
                                                  clumpers
    --show-clumper <clumper>                      Bail and output this clumper's
                                                  detailed usage.
    --filename-key|fk <keyspec>                   Add a key with the source
                                                  filename (if no filename is
                                                  applicable will put NONE)
 
   Help Options:
       --help-aggregators     List the aggregators
       --help-all             Output all help for this script
       --help                 This help screen
       --help-clumping        Help on clumping; mechanisms to group records
                              across a stream
       --help-domainlanguage  Help on the recs domain language, a [very
                              complicated] way of specifying valuations (which
                              act like keys) or aggregators
       --help-keygroups       Help on keygroups, a way of specifying
                              multiple keys
       --help-keys            Help on keygroups and keyspecs
       --help-keyspecs        Help on keyspecs, a way to index deeply and
                              with regexes
       --help-more            Larger help documentation
 
 Examples:
    Count clumps of adjacent lines with matching x fields.
       recs-collate --adjacent --key x --aggregator count
    Count number of each x field value in the entire file.
       recs-collate --key x --aggregator count
    Finds the maximum latency for each date, hour pair
       recs-collate --key date,hour --aggregator worst_latency=max,latency
    Find the median value of x+y in records
       recs-collate --dlaggregator "m=perc(50,snip(<<{{x}}+{{y}}>>))"

=head1 See Also

=over

=item  L<RecordStream(3)> - Overview of the scripts and the system

=item  L<recs-examples(3)> - A set of simple recs examples

=item  L<recs-story(3)> - A humorous introduction to RecordStream

=item SCRIPT --help - every script has a --help option, like the output above

=back

