=head1 NAME

recs-fromxferlog

=head1 recs-fromxferlog --help-all

 Usage: recs-fromxferlog <args>
    Each line of input (or lines of <files>) is parse by Net::FTPServer::XferLog
    to produce an output record.
 
 Examples:
    Get records from typical xferlog
       recs-fromxferlog < /var/log/xferlog

=head1 SEE ALSO

=over

=item * See L<App::RecordStream> for an overview of the scripts and the system

=item * Run C<recs examples> or see L<App::RecordStream::Manual::Examples> for a set of simple recs examples

=item * Run C<recs story> or see L<App::RecordStream::Manual::Story> for a humorous introduction to RecordStream

=item * Every command has a C<--help> mode available to print out usage and
examples for the particular command, just like the output above.

=back

