.TH RECS\-FROMMONGO 1 "2026-02-24" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-frommongo \- Generate records from a MongoDB query

.SH SYNOPSIS
.B recs frommongo --host <URI> --name <DB> --collection <COLL> --query <QUERY>

.SH DESCRIPTION
Generate records from a MongoDB query. Connects to a MongoDB instance, runs the specified query against the given collection, and outputs each matching document as a record.
.PP

.SH OPTIONS
.TP
\fB--host\fR \fI<HOST_URI>\fR
URI for your mongo instance, may include user:pass@URI.
.TP
\fB--user\fR \fI<USER>\fR
User to authenticate as.
.TP
\fB--password\fR, \fB--pass\fR \fI<PASSWORD>\fR
Password for \-\-user.
.TP
\fB--name\fR, \fB--dbname\fR \fI<DB_NAME>\fR
Name of database to connect to.
.TP
\fB--collection\fR \fI<COLLECTION_NAME>\fR
Name of collection to query against.
.TP
\fB--query\fR \fI<QUERY>\fR
JSON query string to run against the collection.

.SH EXAMPLES
Make a query against a MongoDB instance
.PP
.RS 4
.nf
\fBrecs frommongo --host mongodb://user:pass@dharma.mongohq.com:10069 --name my_app --collection my_collection --query \'{doc_key: {$not: {$size: 0}}}\'\fR
.fi
.RE

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

