.TH RECS\-TOHTML 1 "2026-02-24" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-tohtml \- Prints out an HTML table for the records from input or from files

.SH SYNOPSIS
.B recs tohtml [options] [files...]

.SH DESCRIPTION
Prints out an HTML table for the records from input or from files.
.PP

.SH OPTIONS
.TP
\fB--keys\fR, \fB-k\fR, \fB--key\fR, \fB--fields\fR, \fB-f\fR \fI<keys>\fR
Keys to print in the table. May be specified multiple times or comma separated. Defaults to all fields in the first record.
.TP
\fB--noheader\fR
Do not print the header row.
.TP
\fB--rowattributes\fR, \fB--row\fR \fI<attributes>\fR
HTML attributes to put on the tr tags.
.TP
\fB--cellattributes\fR, \fB--cell\fR \fI<attributes>\fR
HTML attributes to put on the td and th tags.

.SH EXAMPLES
Print all fields as an HTML table
.PP
.RS 4
.nf
\fBrecs tohtml\fR
.fi
.RE

Print foo and bar fields, without a header
.PP
.RS 4
.nf
\fBrecs tohtml --fields foo,bar --noheader\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-totable\fR(1), \fBrecs\-toprettyprint\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

