.TH RECS\-FROMPS 1 "2026-02-24" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-fromps \- Generate records from the process table

.SH SYNOPSIS
.B recs fromps [options]

.SH DESCRIPTION
Generate records from the process table. Prints out JSON records converted from the process table. Fields default to all available fields from ps.
.PP

.SH OPTIONS
.TP
\fB--key\fR, \fB-k\fR \fI<fields>\fR
Fields to output. May be specified multiple times, may be comma separated. Defaults to all fields.
.TP
\fB--field\fR, \fB-f\fR \fI<fields>\fR
Fields to output. May be specified multiple times, may be comma separated. Defaults to all fields.

.SH EXAMPLES
Get records for the process table
.PP
.RS 4
.nf
\fBrecs fromps\fR
.fi
.RE

Only get uid and pid
.PP
.RS 4
.nf
\fBrecs fromps --key uid,pid\fR
.fi
.RE

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

