.TH RECS\-SORT 1 "2026-02-23" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-sort \- Sort records from input or from files

.SH SYNOPSIS
.B recs sort [options] [files...]

.SH DESCRIPTION
Sort records from input or from files. You may sort on a list of keys, each key sorted lexically (alpha order) or numerically. The sort type may be prefixed with \'\-\' to indicate decreasing order.
.PP

.SH OPTIONS
.TP
\fB--key\fR, \fB-k\fR \fI<keyspec>\fR
Sort key specification. May be comma\-separated, may be specified multiple times. Each keyspec is a name or name=sortType. Sort type may be lexical, numeric, nat, lex, n, or l. May be prefixed with \'\-\' for decreasing order.
.TP
\fB--reverse\fR, \fB-r\fR
Reverse the sort order.

.SH EXAMPLES
Sort on the id field numerically
.PP
.RS 4
.nf
\fBrecs sort --key id=numeric\fR
.fi
.RE

Sort on age numerically, then name lexically
.PP
.RS 4
.nf
\fBrecs sort --key age=numeric,name\fR
.fi
.RE

Sort on decreasing size, then name
.PP
.RS 4
.nf
\fBrecs sort --key size=-numeric --key name\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-collate\fR(1), \fBrecs\-topn\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

