.TH RECS\-FROMXML 1 "2026-02-24" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-fromxml \- Reads either from STDIN or from the specified URIs

.SH SYNOPSIS
.B recs fromxml [options] [<URIs>]

.SH DESCRIPTION
Reads either from STDIN or from the specified URIs. Parses the XML documents and creates records for the specified elements. If multiple element types are specified, will add an \'element\' field to the output record.
.PP

.SH OPTIONS
.TP
\fB--element\fR \fI<elements>\fR
May be comma separated, may be specified multiple times. Sets the elements/attributes to print records for.
.TP
\fB--nested\fR
Search for elements at all levels of the XML document.

.SH EXAMPLES
Create records for the bar element at the top level of myXMLDoc
.PP
.RS 4
.nf
\fBrecs fromxml --element bar file:myXMLDoc\fR
.fi
.RE

Create records for all foo and bar elements from a URL
.PP
.RS 4
.nf
\fBrecs fromxml --element foo,bar --nested http://google.com\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-fromatomfeed\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

