.TH RECS\-STREAM2TABLE 1 "2026-02-23" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-stream2table \- Transforms a list of records, combining records based on a column field

.SH SYNOPSIS
.B recs stream2table [options] [files...]

.SH DESCRIPTION
Transforms a list of records, combining records based on a column field. In order, the values of the column will be added to the output records. Note: this script spools the stream into memory. The full input record will be associated with the value of the field. The field itself will be removed from the nested record if it is not a key spec.
.PP

.SH OPTIONS
.TP
\fB--field\fR, \fB-f\fR \fI<FIELD>\fR
Field to use as the column key. May be a keyspec.

.SH EXAMPLES
Transform a record stream with each stat on one line to a stream with one value for each stat present on one line
.PP
.RS 4
.nf
\fBrecs stream2table --field stat\fR
.fi
.RE

Combine records by column field
.PP
.RS 4
.nf
\fBrecs stream2table --field column\fR
.fi
.RE
.PP
Input:
.RS 4
.nf
{"column":"foo","data":"foo1"}
{"column":"foo","data":"foo2"}
{"column":"boo","data":"boo1"}
{"column":"boo","data":"boo2"}
.fi
.RE
.PP
Output:
.RS 4
.nf
{"boo":{"data":"boo1"},"foo":{"data":"foo1"}}
{"boo":{"data":"boo2"},"foo":{"data":"foo2"}}
.fi
.RE

.SH SEE ALSO
\fBrecs\-flatten\fR(1), \fBrecs\-collate\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

