.TH RECS\-TOPRETTYPRINT 1 "2026-02-24" "recs 0.1.0" "RecordStream Manual"

.SH NAME
recs\-toprettyprint \- Pretty print records, one key to a line, with a line of dashes separating records

.SH SYNOPSIS
.B recs toprettyprint [options] [files...]

.SH DESCRIPTION
Pretty print records, one key to a line, with a line of dashes separating records. Especially useful for records with very large amounts of keys.
.PP

.SH OPTIONS
.TP
\fB--1\fR, \fB--one\fR
Only print the first record.
.TP
\fB--n\fR \fI<n>\fR
Only print n records.
.TP
\fB--keys\fR, \fB-k\fR \fI<keys>\fR
Only print out specified keys. May be keyspecs or keygroups.
.TP
\fB--nonested\fR
Do not nest the output of hashes, keep each value on one line.
.TP
\fB--aligned\fR \fI[r|l|right|left]\fR
Format keys to the same width so values are aligned. Keys are right aligned by default, but you may pass a value of \'left\' to left align keys within the width.

.SH EXAMPLES
Pretty print records
.PP
.RS 4
.nf
\fBrecs toprettyprint\fR
.fi
.RE

Find all keys with \'time\' in the name or value
.PP
.RS 4
.nf
\fB... | recs toprettyprint --one | grep time\fR
.fi
.RE

.SH SEE ALSO
\fBrecs\-totable\fR(1), \fBrecs\-tohtml\fR(1)

.SH AUTHOR
Benjamin Bernard <perlhacker@benjaminbernard.com>

