#!/bin/sh
# Partially based on maint/build.pl
# from https://github.com/miyagawa/cpanminus (1.7014-4-g4064399),
# licensed under the Artistic 1.0 license.
version=${1:-`git describe --tags HEAD`}

mkdir .fatpack-recs
cp -r fatlib lib .fatpack-recs/

cd .fatpack-recs

echo "Stripping Perl libs (this can take a while)"
find fatlib lib -type f -name '*.pm' -not -path 'lib/App/RecordStream/Manual/*' \
    | xargs perlstrip --size --cache

echo Fatpacking ./bin/recs into ./recs
fatpack file ../bin/recs > ../recs

cd ..

chmod 0755 recs

rm -r .fatpack-recs

echo "Rewriting shebang"
perl -pi -e 's{^#!perl$}{#!/usr/bin/env perl}' recs

echo "Setting version to $version"
perl -pi -e "s/(?<=^our \\\$VERSION)(?=;)/ = '$version'/" recs

echo "Setting fatpack status"
perl -pi -e "s/(?<=^our \\\$FATPACKED = )0(?=;)/1/" recs
